blog/urls.py
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
   File Name：     urls.py  
   Description :  
   Author :       JHao
   date：          2017/4/13
-------------------------------------------------
   Change Activity:
                   2017/4/13: 
-------------------------------------------------
"""
__author__ = 'JHao'

from blog import views
from django.conf.urls import url

urlpatterns = [
    url(r'^index/$', views.Index, name='index'),
    url(r'^about/$', views.About, name='about'),
    url(r'^archive/$', views.archive, name='archive'),
    url(r'^article/(?P<pk>\d+)/$', views.Articles, name='article'),
    url(r'^detail/(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'^detail/(?P<pk>\d+)$', views.detail, name='detail'),
    url(r'^search/$', views.search, name='search'),
    url(r'^tag/(?P<name>.*?)/$', views.tag, name='tag'),

]

django_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^blog/$', views.Index, name='index'),
    url(r'^$', views.Index),

]

blog/models.py
# -*- coding: utf-8 -*-


from django.db import models
from django.conf import settings


# Create  models here.

class Tag(models.Model):
    tag_name = models.CharField(u'标签名', max_length=30)

    def __str__(self):
        return self.tag_name


class Article(models.Model):
    title = models.CharField(max_length=200)  # 标题
    category = models.ForeignKey('Category', verbose_name=u'文章类型', on_delete=models.CASCADE)
    date_time = models.DateField(auto_now_add=True)  # 日期
    content = models.TextField(blank=True, null=True)  # 正文
    digest = models.TextField(blank=True, null=True)  # 文章摘要
    author = models.TextField(blank=True, null=True)
    view = models.BigIntegerField(default=0)  # 阅读数
    comment = models.BigIntegerField(default=0)  # 评论数
    picture = models.CharField(max_length=200)  # 标题图片地址
    tag = models.ManyToManyField(Tag)  # 标签

    def __str__(self):
        return self.title

    def sourceUrl(self):
        source_url = settings.HOST + '/blog/detail/{id}'.format(id=self.pk)
        return source_url  # 给网易云跟帖使用

    def viewed(self):
        """
        增加阅读数
        :return:
        """
        self.view += 1
        self.save(update_fields=['view'])

    def commenced(self):
        """
        增加评论数
        :return:
        """
        self.comment += 1
        self.save(update_fields=['comment'])

    class Meta:  # 按时间降序
        ordering = ['-date_time']


class Category(models.Model):
    name = models.CharField(u'文章类型', max_length=30)
    created_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField(u'修改时间', auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = u"文章类型"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Comment(models.Model):
    title = models.CharField(u"标题", max_length=100)
    source_id = models.CharField(u'文章id或source名称', max_length=25)
    create_time = models.DateTimeField(u'评论时间', auto_now=True)
    user_name = models.CharField(u'评论用户', max_length=25)
    url = models.CharField(u'链接', max_length=100)
    comment = models.CharField(u'评论内容', max_length=500)

blog/views.py
# -*- coding: utf-8 -*-
# Create your views here.

import json
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from blog.models import Article, Category, Comment


def Index(request):
    """
    博客首页
    :param request:
    :return:
    """
    article_list = Article.objects.all().order_by('-date_time')[0:5]
    return render(request, 'blog/index.html', {"article_list": article_list,
                                               "source_id": "index"})


def Articles(request, pk):
    """
    博客列表页面
    :param request:
    :param pk:
    :return:
    """
    pk = int(pk)
    if pk:
        category_object = get_object_or_404(Category, pk=pk)
        category = category_object.name
        article_list = Article.objects.filter(category_id=pk)
    else:
        # pk为0时表示全部
        article_list = Article.objects.all()  # 获取全部文章
        category = u''
    return render(request, 'blog/articles.html', {"article_list": article_list,
                                                  "category": category,
                                                  })


def About(request):
    return render(request, 'blog/about.html')

#归档
def archive(request):
    article_list = Article.objects.order_by('-date_time')
    return render(request, 'blog/archive.html', {"article_list": article_list})




@csrf_exempt
def GetComment(request):
    """
    接收畅言的评论回推， post方式回推
    :param request:
    :return:
    """
    arg = request.POST
    data = arg.get('data')
    data = json.loads(data)
    title = data.get('title')
    url = data.get('url')
    source_id = data.get('sourceid')
    if source_id not in ['message']:
        article = Article.objects.get(pk=source_id)
        article.commenced()
    comments = data.get('comments')[0]
    content = comments.get('content')
    user = comments.get('user').get('nickname')
    Comment(title=title, source_id=source_id, user_name=user, url=url, comment=content).save()
    return JsonResponse({"status": "ok"})


def detail(request, pk):
    """
    博文详情
    :param request:
    :param pk:
    :return:
    """
    article = get_object_or_404(Article, pk=pk)
    article.viewed()
    return render(request, 'blog/detail.html', {"article": article,
                                                "source_id": article.id})


def search(request):
    """
    搜索
    :param request:
    :return:
    """
    try:
        key = request.GET['key']
        article_list = Article.objects.filter(title__contains=key)
        return render(request, 'blog/search.html',
                      {"article_list": article_list, "key": key})
    except:
        keys = ''
        return



def tag(request, name):
    """
    标签
    :param request:
    :param name
    :return:
    """
    article_list = Article.objects.filter(tag__tag_name=name)
    return render(request, 'blog/tag.html', {"article_list": article_list,
                                             "tag": name})

templates/blog/about.html
{% extends "blog/base.html" %}

{% block title %}
    <title>AboutMe</title>
{% endblock %}

{% block content %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">页面建设中。。。。</section>

{% endblock %}

templates/blog/archive.html
{% extends "blog/base.html" %}
{% load custom_filter %}

{% block title %}
    <title>文章归档</title>
{% endblock %}

{% block css %}
    <link href="/static/archives/style.css" rel="stylesheet"/>
{% endblock %}

{% block content %}
    <section class="mysection main" style="animation: fuxiasuo 0.8s;">
        <ul class="timeline">
            {% for article in article_list %}
                <li class="event">
                    <input type="radio" name="tl-group" {% if forloop.counter0 == 0 %} checked {% endif %}/>
                    <label></label>
                    <div class="thumb"><span>{{ article.date_time }}</span></div>
                    <div class="content-perspective">
                        <div class="content">
                            <div class="content-inner">
                                <h3><a href="{% url "blog:detail" pk=article.id%}">{{ article.title }}</a></h3>
                                <p>{{ article.digest }}</p>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

templates/blog/articles.html
{% extends "blog/base.html" %}
{% load custom_filter %}

{% block title %}
    <title>文章列表</title>
{% endblock %}

{% block content %}
    {% paginate article_list 8 %}
    {% if article_list %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "blog:article" pk=0 %}"><i class="el-th-list"></i>{% if category %}列表{% else %} 全部 {% endif %} &nbsp;&nbsp;> &nbsp;&nbsp;</a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">共有文章:<a class="orange-text"> {{ count }} </a>篇</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.view > 500 %}id="tuijian"{% elif article.view > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ article.picture }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "blog:detail" pk=article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.date_time }} 发表 "><i class="el-time"></i> {{ article.date_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>

                            </li>
                            <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "blog:article" pk=article.category_id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>

                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>
    {% else %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section>
    {% endif %}

{% endblock %}

templates/blog/detail.html
{% extends "blog/base.html" %}
{% load custom_filter %}

{% block title %}
    <title>{{ article.title }}文章</title>
{% endblock %}

{% block meta %}
    <meta name="keywords"
          content="{{ article.title }},{% for tag in article.tag.all %}{{ tag }},{% endfor %}{{ article.category }}"/>
    <meta name="description" content="{{ article.digest|safe }}"/>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/css/markdown.css">
    <link rel="stylesheet" href="/static/prism/prism.css">

    <script src="/static/prism/prism.js" charset="utf-8"></script>

    <script type="text/javascript"
            src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {inlineMath: [['$', '$']]},
            messageStyle: "none"
        });


    </script>

{% endblock %}

{% block content %}

    <div class="mysection content">
        <article>
            <h3 class="arc-title index-title">{{ article.title }} </h3>
            <div class="post-line bg-color">
                <ul>
                    <li><a title="{{ article.author }}发表于{{ article.date_time }}"><i class="el-time"></i>
                        <time>{{ article.date_time }}</time>
                    </a></li>
                    <li><a href="#"><i class="el-user"></i>{{ article.author }}</a></li>
                    <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                </ul>
            </div>

            <!--文章正文-->
            <div class="article-content bg-color markdown-body">
                <div class="post-content" style="padding: 10px 20px 20px 10px">
                    <div class="BlogAnchor" style="text-indent: 20px; font-size: 14px; margin-bottom: 30px">
                        <p>
                            <b id="AnchorContentToggle" title="收起" style="cursor:pointer;"></b>
                        </p>
                        <div class="AnchorContent" id="AnchorContent"></div>
                    </div>
                    {{ article.content|custom_markdown|safe }}
                </div>
            </div>

            <!--标签-->
            <div class="article_tag">
                <ul>
                    <li><a href="{% url "blog:article" pk=article.category_id %}"
                           title="归类：{{ article.category }}">{{ article.category }}</a></li>
                    {% for tag in article.tag.all %}
                        <li><a href="{% url "blog:tag" name=tag.tag_name %}"
                               title="标签：{{ tag.tag_name }} ">{{ tag.tag_name }}</a>&nbsp;
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="cyEmoji" style="text-align: center">
                <div id="cyEmoji" role="cylabs" data-use="emoji" sid="{{ source_id }}"></div>
            </div>

        </article>
        <hr>

        <script type="text/javascript" charset="utf-8" src="https://changyan.itc.cn/js/lib/jquery.js"></script>
        <script type="text/javascript" charset="utf-8"
                src="https://changyan.sohu.com/js/changyan.labs.https.js?appid=cyt6A5N47"></script>
    </div>


{% endblock %}

templates/blog/footer.html
<footer>
    <!--底部导航-->
    <div class="foot-nav">
        <div class="copy-right"><span> &#169; 2018-5-20 文献管理系统 &#160;&#160;&#160;     </span></div>

    </div>
    <div id="toTop">Back to Top</div>
    <script>
    </script>


</footer>

templates/blog/header.html
<header class="myheader">
    <div class="top">
        <!--头像左边部分-->
        <div class="top-left">
            <div class="logo"><a href="/"><img src="/static/images/h.gif"/></a></div>

            <!--滚动消息-->
            <div class="web-xiaoxi">
                <i class="el-speaker"></i>
                <ul class="mulitline">
                    <li style="color: #4286F3 ">欢迎进入文献管理系统</li>
                    <li style="color: #EB4537 ">欢迎进入文献管理系统</li>
                    <li style="color: #FAC230 ">欢迎进入文献管理系统</li>
                </ul>
            </div>
            <!--END 消息 -->


        </div>
        <!--导航开始-->
        <nav class="mynav">
            <ul class="orange-text">
                <li class=""><a href="{% url "blog:index" %}">首页</a></li>
                
                <li><a href="{% url "blog:article" pk=0 %}">文章</a></li>
                <li class='drop'>
                    <a href="JavaScript:;">分类<i class='el-chevron-down'></i></a>
                    <div class="drop-nav orange-text ">
                        <ul>
                            {% for category in category_list %}
                                <li><a href="{% url "blog:article" pk=category.pk %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li><a href="{% url "blog:archive" %}">归档</a></li>

            </ul>
        </nav>


    </div>

<!--换肤--->
    <script src="/static/js/skin.js"></script>
    <div class="select-skin" style="visibility: hidden">
        <div class="skin-btn">
            <a href="javascript:void(0);" class="skin-btn-open">换<br>肤</a>
        </div>

        <div class="skin-content">
            <h1>选择风格<span class="skin-close">关闭</span></h1>
            <div class="skin-content-list">
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingxin'); return false;" class="btn1">清新</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('jianyue'); return false;" class="btn2">简约</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingshuang'); return false;"
                                          class="btn3">清爽</a></div>
            </div>
        </div>
    </div>
</header>

templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}

<section class="mysection">


    <div class="arclist">
        <h4 class="index-title homeh4"><a href=""><i class="el-certificate"></i>最新文章
            <small>New Article</small>
        </a></h4>
        <!--列表开始-->
        <ul>
            {% for article in article_list %}
            <li id="New">
                <div class="arcimg">
                    <img src="{{ article.picture }}" alt="{{ article.title }}" title="{{ article.title }}"/>
                </div>
                <div class="arc-right">
                    <h4 class="blue-text"><a href="{% url "blog:detail" pk=article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                    <p>{{ article.digest }}</p>
                    <ul>
                        <li><a title="{{ article.author }}{{ article.date_time }} 发表 "><i
                                class="el-time"></i> {{ article.date_time }}</a></li>
                        <li><a href="#" title="作者： {{ article.author }}"><i
                                class="el-user"></i>{{ article.author }}</a></li>

                        </li>
                        <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}
                        </a></li>
                        <li><a href="#" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                    </ul>
                </div>
            </li>
            {% endfor %}
        </ul>
        <!--列表结束-->
        </div>

    <div class="arclist">
        <h4 class="index-title homeh4"><a href=""><i class="el-certificate"></i>最热文章
            <small>Hot Article</small>
        </a></h4>
        <!--列表开始-->
        <ul>
            {% for article in article_rank %}
            <li id="Hot">
                <div class="arcimg">
                    <img src="{{ article.picture }}" alt="{{ article.title }}" title="{{ article.title }}"/>
                </div>
                <div class="arc-right">
                    <h4 class="blue-text"><a href="{% url "blog:detail" pk=article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                    <p>{{ article.digest }}</p>
                    <ul>
                        <li><a title="{{ article.author }}{{ article.date_time }} 发表 "><i
                                class="el-time"></i> {{ article.date_time }}</a></li>
                        <li><a href="#" title="作者： {{ article.author }}"><i
                                class="el-user"></i>{{ article.author }}</a></li>
                        <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}
                        </a></li>
                        <li><a href="#" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                    </ul>
                </div>
            </li>
            {% endfor %}
        </ul>
        <!--列表结束-->
        </div>
</section>

{% endblock %}

templates/blog/message.html
<h3 class="form-btn blue-text"><a href="javascript:;"><i class="el-edit"></i>我要留言 / 展开表单</a></h3>
<div id="Coon" class="form-zd form-in">
    <div id="SOHUCS" sid="{{ source_id }}"></div>
    <script type="text/javascript">
        (function () {
            var appid = 'cytC2mmED';
            var conf = 'prod_ff0a9edf5e5fdf3a02644715b9080454';
            var width = window.innerWidth || document.documentElement.clientWidth;
            if (width < 960) {
                window.document.write('<script id="changyan_mobile_js" charset="utf-8" type="text/javascript" src="https://changyan.sohu.com/upload/mobile/wap-js/changyan_mobile.js?client_id=' + appid + '&conf=' + conf + '"><\/script>');
            } else {
                var loadJs = function (d, a) {
                    var c = document.getElementsByTagName("head")[0] || document.head || document.documentElement;
                    var b = document.createElement("script");
                    b.setAttribute("type", "text/javascript");
                    b.setAttribute("charset", "UTF-8");
                    b.setAttribute("src", d);
                    if (typeof a === "function") {
                        if (window.attachEvent) {
                            b.onreadystatechange = function () {
                                var e = b.readyState;
                                if (e === "loaded" || e === "complete") {
                                    b.onreadystatechange = null;
                                    a()
                                }
                            }
                        } else {
                            b.onload = a
                        }
                    }
                    c.appendChild(b)
                };
                loadJs("https://changyan.sohu.com/upload/changyan.js", function () {
                    window.changyan.api.config({appid: appid, conf: conf})
                });
            }
        })(); </script>

</div>

templates/blog/right.html
<aside class="myaside">
    <!--关注我-->
    <div class="focus-me bg-color animation-div">

    </div>
    <!--最新更新-->

    <div class="clos-new bg-color animation-div">
        <h4 class="index-title"><i class="el-bulb"></i>最新资讯
            <small>Latest News</small>
        </h4>
        <ul>
            <li><i class="el-cloud"></i>
                <iframe id="tianqi" scrolling="no" frameborder="0" allowtransparency="true"
                        src="http://i.tianqi.com/index.php?c=code&a=getcode&id=34&h=25&w=280"></iframe>
            </li>

            <li><i class="el-calendar"></i>历史今天：
                <iframe src="http://www.todayonhistory.com/code/6.html?w=250&h=20&bky=dotted&bks=0&fs=14&fc=#565656&hg=14&ie=0&xhx=none&sd=300&px=3&len=0&sk=1&n=0"
                        width="250" height="15" scrolling="no" frameborder="0" allowtransparency="true"></iframe>
            </li>
        </ul>
    </div>
    <!--搜索-->
    <div class="search animation-div">
        <form action="{% url "blog:search" %}" method="get">
            <div class="search-index">
                <input name="key" type="text" placeholder="请输入关键字" onfocus="this.placeholder=''"
                       onblur="this.placeholder='请输入关键字'"/>
                <i class="el-search"><input value=" " type="submit"/></i>
            </div>
        </form>
    </div>



    <!--标签-->
    <div class="cloud bg-color animation-div">
        <h4 class="index-title"><i class="el-tags"></i>标签云
            <small>Tags Clouds</small>
        </h4>
        <ul id="3dcloud">
            {% for tag in tag_list %}
                <li><a href="{% url "blog:tag" name=tag.tag_name %}" title="标签：{{ tag.tag_name }} ">{{ tag.tag_name }}</a></li>
            {% endfor %}
        </ul>
    </div>

</aside>

templates/blog/search.html
{% extends "blog/base.html" %}

{% block title %}
    <title>搜索:{{ key }}</title>
{% endblock %}

{% load custom_filter %}
{% block content %}
    {% paginate article_list 8 %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "blog:article" pk=0 %}"><i class="el-search"></i> 搜索到<b class="lable">{{ key }}</b>相关结果</a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">共:<a class="orange-text"> {{ count }} </a>条</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.view > 500 %}id="tuijian"{% elif article.view > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ article.picture }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "blog:detail" pk=article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.date_time }} 发表 "><i class="el-time"></i> {{ article.date_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>

                            <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "blog:article" pk=article.category_id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>

    </section>

{% endblock %}

templates/blog/tag.html
{% extends "blog/base.html" %}
{% load custom_filter %}

{% block title %}
    <title>标签：{{ tag }}</title>
{% endblock %}

{% block content %}
    {% paginate article_list 8 %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "blog:article" pk=0 %}"><i class="el-tag"></i> 标签<b class="lable">{{ tag }}</b></a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">共有:<a class="orange-text"> {{ count }} </a>篇</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.view > 500 %}id="tuijian"{% elif article.view > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ article.picture }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "blog:detail" pk=article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.date_time }} 发表 "><i class="el-time"></i> {{ article.date_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>

                            </li>
                            <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "blog:article" pk=article.category_id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>

                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>

{% endblock %}